# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 07:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailauthuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 17, 13, 1, 56, 482176), verbose_name='date joined'),
        ),
    ]
